### ISSUE TITLE
only one playlist exported?

### ISSUE THREAD

**Issue by joshwhitk** [thisispiggy/gmusicchecker#2]
I am a junior python coder, so bear with me please.

I was able to run musicchecker.py successfully, multiple times. (login, download, and update library.json).   
When I ran playlists.py, it ran successfully apparently, but playlists.json only seemed to contain one playlist. (I expected all my playlists).   Did I misunderstand how playlists.py works, or is there a bug?

**Comment by kangruixiang** [comment]
Hey originally I wrote playlists.py for myself to pull out songs for one playlist instead of sharing it publicly. You have to enter which playlist you want to extract. There’s probably a way to get all the playlists. I’m currently too busy to work on that. Maybe in the future I’ll have some free time.
